mongodb:
  host: localhost
  port: 27017

cache:
  filename: 'instance.db'

projects:
  FRA:
    auth_url: 'http://api.fr.cloudopen.com.br:35357'
    auth_user: zabbix
    auth_pass: qbXFWHjBZD6S
    auth_tentant: 'B2W Digital'
    all_tentants: true
  ESP:
    auth_url: 'http://api.es.cloudopen.com.br:35357'
    auth_user: zabbix
    auth_pass: qbXFWHjBZD6S
    auth_tentant: 'B2W Digital'
    all_tentants: true
